apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
          - role: endpoints
          # Add namespace configuration
          namespaces:
            names:
              - kube-system  # Specify kube-system namespace where CoreDNS runs
        relabel_configs:
          # Keep only coredns endpoints
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: coredns
          # Set metrics path
          - source_labels: []
            target_label: __metrics_path__
            replacement: /metrics
          # Add useful labels
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_service