apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring  # Replace with your Prometheus namespace
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Scraping Kubernetes Services with Prometheus annotations
      - job_name: 'flask-app-metrics'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          # Match the service name
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: "backend"  # This should match your service name

          # Ensure Prometheus scrapes the service
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"  # Ensures that services with this annotation are scraped

          # Set the metrics path to "/metrics" from the annotation
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: "(.*)"
            replacement: "/metrics"  # Path should be '/metrics'

          # Set the port from the service annotation (5000 in this case)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: "(.*)"
            replacement: "$1:5000"  # Use internal port 5000 for scraping