apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Kubernetes Service Discovery (default config)
      - job_name: 'flask-app-metrics'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: "your-flask-app-label"
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: __address__
            regex: "(.*)"
            replacement: "$1:5000"  # Assuming the Flask app is running on port 5000
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: "(.*)"
            replacement: "/metrics"  # Flask metrics endpoint