serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'backend-service'
        static_configs:
          - targets: ['backend.default.svc.cluster.local:5000']
        metrics_path: '/metrics'
        scrape_interval: 15s
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true