apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: k8s-backend
          image: 471112618713.dkr.ecr.us-east-1.amazonaws.com/backend_repo:21
          ports:
            - containerPort: 5005
          envFrom:
            - configMapRef:
                name: app-config