apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: k8s-frontend
          image: 471112618713.dkr.ecr.us-east-1.amazonaws.com/frontend_repo:6
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config