apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-credentials  # Make sure the secret exists in the cluster
      containers:
        - name: k8s-backend
          image: 471112618713.dkr.ecr.us-east-1.amazonaws.com/backend_repo:80
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
